import type { ResearchNode } from '../sim/types';

export const RESEARCH_TREE: ResearchNode[] = [
  // ── Tier 1: Basic ──
  { id: 'basic_smelting', name: 'Basic Smelting', description: 'Unlock the Smelter to process ores.', branch: 'processing',
    cost: [{ resource: 'iron_ore', amount: 20 }], ticksRequired: 300, prerequisites: [], unlocks: ['smelter'] },
  { id: 'logistics_1', name: 'Logistics I', description: 'Unlock splitters and mergers.', branch: 'logistics',
    cost: [{ resource: 'iron_ore', amount: 15 }], ticksRequired: 200, prerequisites: [], unlocks: ['splitter', 'merger'] },
  { id: 'power_storage', name: 'Power Storage', description: 'Unlock storage bins.', branch: 'logistics',
    cost: [{ resource: 'iron_ore', amount: 10 }], ticksRequired: 150, prerequisites: [], unlocks: ['storage'] },
  { id: 'cave_surveying', name: 'Cave Surveying', description: 'Improved cave awareness. Unlock radar.', branch: 'stability',
    cost: [{ resource: 'stone', amount: 20 }], ticksRequired: 200, prerequisites: [], unlocks: ['radar'] },

  // ── Tier 2: Intermediate ──
  { id: 'advanced_mining', name: 'Advanced Mining', description: 'Unlock advanced drill with higher speed.', branch: 'mining',
    cost: [{ resource: 'iron_ingot', amount: 10 }, { resource: 'copper_ingot', amount: 5 }], ticksRequired: 500, prerequisites: ['basic_smelting'], unlocks: ['advanced_drill'] },
  { id: 'refining', name: 'Refining', description: 'Unlock refinery for steel and advanced materials.', branch: 'processing',
    cost: [{ resource: 'iron_ingot', amount: 15 }, { resource: 'coal', amount: 10 }], ticksRequired: 600, prerequisites: ['basic_smelting'], unlocks: ['refinery'] },
  { id: 'assembly', name: 'Assembly', description: 'Unlock assembler for components.', branch: 'processing',
    cost: [{ resource: 'copper_ingot', amount: 15 }], ticksRequired: 500, prerequisites: ['basic_smelting'], unlocks: ['assembler'] },
  { id: 'energy_storage', name: 'Energy Storage', description: 'Unlock battery banks.', branch: 'power',
    cost: [{ resource: 'copper_ingot', amount: 10 }, { resource: 'iron_ingot', amount: 5 }], ticksRequired: 400, prerequisites: ['basic_smelting'], unlocks: ['battery'] },
  { id: 'efficient_power', name: 'Efficient Power', description: 'Unlock transformers to reduce line loss.', branch: 'power',
    cost: [{ resource: 'copper_ingot', amount: 15 }], ticksRequired: 400, prerequisites: ['energy_storage'], unlocks: ['transformer'] },
  { id: 'cave_engineering', name: 'Cave Engineering', description: 'Unlock rock bolters for better stability.', branch: 'stability',
    cost: [{ resource: 'iron_ingot', amount: 10 }, { resource: 'stone', amount: 20 }], ticksRequired: 400, prerequisites: ['cave_surveying'], unlocks: ['rock_bolter'] },
  { id: 'advanced_cooling', name: 'Advanced Cooling', description: 'Unlock heat exchangers.', branch: 'cooling',
    cost: [{ resource: 'copper_ingot', amount: 10 }, { resource: 'ice', amount: 15 }], ticksRequired: 500, prerequisites: ['basic_smelting'], unlocks: ['heat_exchanger'] },
  { id: 'radar_scanning', name: 'Radar Scanning', description: 'Unlock radar scanner to find ores.', branch: 'stability',
    cost: [{ resource: 'circuit', amount: 3 }], ticksRequired: 400, prerequisites: ['cave_surveying', 'assembly'], unlocks: ['radar'] },

  // ── Tier 3: Advanced ──
  { id: 'gas_power', name: 'Gas Power', description: 'Unlock gas generators.', branch: 'power',
    cost: [{ resource: 'steel', amount: 10 }, { resource: 'circuit', amount: 5 }], ticksRequired: 800, prerequisites: ['refining', 'assembly'], unlocks: ['gas_generator'] },
  { id: 'blast_mining', name: 'Blast Mining', description: 'Unlock blast miner. Dangerous but productive.', branch: 'mining',
    cost: [{ resource: 'explosives', amount: 10 }, { resource: 'steel', amount: 5 }], ticksRequired: 800, prerequisites: ['advanced_mining', 'refining'], unlocks: ['blast_miner'] },
  { id: 'maintenance_network', name: 'Maintenance Network', description: 'Unlock maintenance hub for wear reduction.', branch: 'logistics',
    cost: [{ resource: 'spare_parts', amount: 10 }, { resource: 'circuit', amount: 5 }], ticksRequired: 600, prerequisites: ['assembly'], unlocks: ['maintenance_hub'] },
  { id: 'cryo_cooling', name: 'Cryogenic Cooling', description: 'Unlock cryo units for extreme cooling.', branch: 'cooling',
    cost: [{ resource: 'coolant', amount: 10 }, { resource: 'steel', amount: 10 }], ticksRequired: 800, prerequisites: ['advanced_cooling', 'refining'], unlocks: ['cryo_unit'] },
  { id: 'contracts_plus', name: 'Contracts+', description: 'Better contract rewards and more options.', branch: 'commerce',
    cost: [{ resource: 'circuit', amount: 5 }, { resource: 'gold_ingot', amount: 3 }], ticksRequired: 500, prerequisites: ['assembly'], unlocks: ['contracts_upgrade'] },

  // ── Tier 4: Expert ──
  { id: 'nuclear_power', name: 'Nuclear Power', description: 'Unlock nuclear reactor. Extreme power, extreme heat.', branch: 'power',
    cost: [{ resource: 'advanced_circuit', amount: 5 }, { resource: 'uranium_rod', amount: 3 }, { resource: 'steel', amount: 20 }],
    ticksRequired: 1500, prerequisites: ['gas_power', 'cryo_cooling'], unlocks: ['nuclear_reactor'] },
  { id: 'deep_mining', name: 'Deep Mining', description: '+50% mining speed on all rigs.', branch: 'mining',
    cost: [{ resource: 'advanced_circuit', amount: 3 }, { resource: 'explosives', amount: 10 }],
    ticksRequired: 1000, prerequisites: ['blast_mining'], unlocks: ['deep_mining_upgrade'] },
  { id: 'automation_2', name: 'Automation II', description: '+50% conveyor throughput.', branch: 'logistics',
    cost: [{ resource: 'advanced_circuit', amount: 5 }, { resource: 'steel', amount: 10 }],
    ticksRequired: 800, prerequisites: ['maintenance_network'], unlocks: ['logistics_upgrade'] },
  { id: 'efficient_smelting', name: 'Efficient Smelting', description: 'Smelters use 25% less input.', branch: 'processing',
    cost: [{ resource: 'research_pack', amount: 5 }], ticksRequired: 600, prerequisites: ['refining'], unlocks: ['efficient_smelting_upgrade'] },
  { id: 'market_mastery', name: 'Market Mastery', description: '+15% sell price at terminals.', branch: 'commerce',
    cost: [{ resource: 'research_pack', amount: 5 }, { resource: 'gold_ingot', amount: 5 }],
    ticksRequired: 800, prerequisites: ['contracts_plus'], unlocks: ['market_upgrade'] },

  // ── Tier 5: Mastery ──
  { id: 'quantum_drill', name: 'Quantum Drilling', description: 'Mining rigs extract 2x resources.', branch: 'mining',
    cost: [{ resource: 'energy_cell', amount: 3 }, { resource: 'advanced_circuit', amount: 5 }],
    ticksRequired: 2000, prerequisites: ['deep_mining'], unlocks: ['quantum_mining_upgrade'] },
  { id: 'fusion_theory', name: 'Fusion Theory', description: 'Reactors produce 50% more power.', branch: 'power',
    cost: [{ resource: 'energy_cell', amount: 5 }, { resource: 'research_pack', amount: 10 }],
    ticksRequired: 2000, prerequisites: ['nuclear_power'], unlocks: ['fusion_upgrade'] },
  { id: 'nanorepair', name: 'Nano-Repair', description: 'All buildings wear 50% slower.', branch: 'logistics',
    cost: [{ resource: 'advanced_circuit', amount: 10 }, { resource: 'crystal', amount: 5 }],
    ticksRequired: 1500, prerequisites: ['automation_2'], unlocks: ['nanorepair_upgrade'] },
  { id: 'zero_waste', name: 'Zero Waste Processing', description: 'Processing buildings have 20% chance of no input consumed.', branch: 'processing',
    cost: [{ resource: 'research_pack', amount: 10 }, { resource: 'energy_cell', amount: 2 }],
    ticksRequired: 1500, prerequisites: ['efficient_smelting'], unlocks: ['zero_waste_upgrade'] },
  { id: 'seismic_dampener', name: 'Seismic Dampening', description: '+50% stability everywhere.', branch: 'stability',
    cost: [{ resource: 'advanced_circuit', amount: 5 }, { resource: 'steel', amount: 20 }],
    ticksRequired: 1200, prerequisites: ['cave_engineering'], unlocks: ['seismic_upgrade'] },
  { id: 'thermal_mastery', name: 'Thermal Mastery', description: 'All heat generation reduced 30%.', branch: 'cooling',
    cost: [{ resource: 'coolant', amount: 20 }, { resource: 'energy_cell', amount: 2 }],
    ticksRequired: 1200, prerequisites: ['cryo_cooling'], unlocks: ['thermal_upgrade'] },
  { id: 'trade_empire', name: 'Trade Empire', description: 'Contracts pay 2x. Market swings reduced.', branch: 'commerce',
    cost: [{ resource: 'energy_cell', amount: 3 }, { resource: 'gold_ingot', amount: 10 }],
    ticksRequired: 1500, prerequisites: ['market_mastery'], unlocks: ['trade_upgrade'] },
  { id: 'overclock', name: 'Overclock', description: 'All machines run 25% faster but 50% more heat.', branch: 'processing',
    cost: [{ resource: 'energy_cell', amount: 5 }, { resource: 'advanced_circuit', amount: 10 }],
    ticksRequired: 2000, prerequisites: ['zero_waste', 'thermal_mastery'], unlocks: ['overclock_upgrade'] },
  { id: 'endgame_automation', name: 'Full Automation', description: 'Repair bays work 3x faster.', branch: 'logistics',
    cost: [{ resource: 'energy_cell', amount: 5 }, { resource: 'research_pack', amount: 15 }],
    ticksRequired: 2500, prerequisites: ['nanorepair', 'quantum_drill'], unlocks: ['full_auto_upgrade'] },
  { id: 'singularity', name: 'Singularity', description: 'Endgame: all production doubled. Victory condition.', branch: 'processing',
    cost: [{ resource: 'energy_cell', amount: 10 }, { resource: 'research_pack', amount: 20 }, { resource: 'advanced_circuit', amount: 15 }],
    ticksRequired: 5000, prerequisites: ['endgame_automation', 'overclock', 'fusion_theory'], unlocks: ['singularity_victory'] },
];
